# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27d4920b7a07778d89e7e616cfd1a03f6e1e110109bac634fc5b2c3f5c77bf99b0716ae78e3c67b35f6b126068c4f7c5a285c129558b26e3348de8360c7048c9

test:
  secret_key_base: 249d85d4e56fefa2e36e02e0bf133a9934f3520d5fb499bf90f08b147081ddd032464c1f0f7e1a4c206f889fdd857e3bcde75e4f74e777128e975cbd95090ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
